server:
  port: 8083
spring:
  application:
    name: b-item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/balabala
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis:
  type-aliases-package: com.balabala.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/*.xml